### ISSUE TITLE
Set repository

### ISSUE THREAD

**Issue by MiketheChap** [elementary/switchboard-plug-about#144]
Elementary is very nice to use. But, there should be a means to set repositories that does not require using the terminal. Ubuntu has an easy to use GUI method to do this.

**Comment by danrabbit** [comment]
We intentionally don't ship tools to edit apt software sources. The preferred method for side loading 3rd party apps is via Flatpak. When installed with Sideload, Flatpak apps will automatically configure their remotes

Closing as "design conflict" since this would contradict the intended way to install 3rd party apps
