### ISSUE TITLE
Add detail page for firmware releases

### ISSUE THREAD

**Issue by meisenzahl** [elementary/switchboard-plug-about#172]
## Problem

Currently I only see a list of available firmware updates. But I don't know what the respective firmware update changes in detail.

![Bildschirmfoto von 2021-01-24 08 25 42](https://user-images.githubusercontent.com/10796736/105623911-cb220900-5e1d-11eb-8746-90b5235bb949.png)

## Proposal

Add a detail page for firmware releases.

## Prior Art

This is a screenshot of [GNOME Firmware](https://gitlab.gnome.org/hughsie/gnome-firmware-updater) showing available information of a release.

![Bildschirmfoto von 2021-01-24 08 21 38](https://user-images.githubusercontent.com/10796736/105623847-4f27c100-5e1d-11eb-983c-bae9d25b3dec.png)

**Comment by cassidyjames** [comment]
@meisenzahl as an initial pass, clicking the row of an update should switch a stack to this view. At a glance, we probably want to include:

- Version
- Summary
- Description
- Vendor
- Size
- Install duration

Rough whiteboard sketch:

![PXL_20201214_193021427 NIGHT](https://user-images.githubusercontent.com/611168/105778633-f72ab080-5f29-11eb-8837-a9e6fd08299c.jpg)


Rough ASCII mockup (inside the stack):

```
[← All Updates ]    Unifying Receiver    [ Install ]
----------------------------------------------------

 ICON  Unifying Receiver
 ICON  A miniaturised USB wireless receiver


Summary here, maybe in bold

Description goes here; it's usually pretty long-form
and includes information about what's in this
release of the update, so we should show it up top.

                  Version: RQR24.06_B0030
                   Vendor: Logitech
                     Size: 56.8 kB
Estimated time to install: 30 sec
```

Honestly we probably don't _need_ the dialog-style icon, primary text, and secondary text up top since we can have the name of the device in the bar up top (see the installer, initial-setup, or adding a keyboard layout in the Keyboard plug for the sort of pattern here).
