### ISSUE TITLE
11th-gen Intel graphics just show as "Intel"

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-about#217]
I think this should be Intel Xe? I can look up the exact specs if it's helpful.

![Screenshot from 2021-05-28 15-53-33@2x](https://user-images.githubusercontent.com/611168/120045354-08192a80-bfcd-11eb-82b9-2b5476637fd2.png)

**Comment by davidmhewitt** [comment]
What does switcheroo have as the name when you look at it's dbus interface with d-feet or whatever?

**Comment by cassidyjames** [comment]
I couldn't find a way to copy it directly, but I think this is the right property? It looks pretty generic.

![Screenshot from 2021-05-28 16-08-27@2x](https://user-images.githubusercontent.com/611168/120046240-ff295880-bfce-11eb-9dce-d72a2c39fc59.png)

**Comment by davidmhewitt** [comment]
Yep, that's the one. The cleanup routines in the plug map "Intel Corporation" to "Intel®". There's also a property on org.gnome.SessionManager, called renderer I think. Does that have any better idea of what the GPU is?

**Comment by cassidyjames** [comment]
Yep, it does list Xe there

![Screenshot from 2021-05-28 16-18-16@2x](https://user-images.githubusercontent.com/611168/120046860-58de5280-bfd0-11eb-8072-2f9c1640f22e.png)

**Comment by davidmhewitt** [comment]
Well, it's coded to prefer getting the info from switcheroo since it tends to return better info than the renderer string, even on single GPU machines.

Would need to look at how Switcheroo gets this info, whether they've already fixed the detection of Xe or whether we need to report a bug/submit a fix.

I guess we could special case a fallback to GNOME SessionManager in the plug in the mean time, but that section of the code is already reasonably complex and it gets even more complex in the what do you do if you've got 2 GPUs and one of them is Xe case.

**Comment by vjr** [comment]
I noticed that my cpu has an upper case X in the model name which gets changed to a small multiplication x symbol. I wonder if something similar is causing the gpu name to be truncated?
