### ISSUE TITLE
Fund elementary OS

### ISSUE THREAD

**Issue by ghost** [elementary/switchboard-plug-about#60]
So I had an idea. How about implementing a new button under the "About" section of the Switchboard that allows users to donate to the elementary OS team anytime they want using the Stripe method that we have in the AppCenter? I would probably donate more, and if it is in the about section, it won't be too intrusive, but it will still make it just as easy to donate to the team that makes all this possible as it is to donate to the devs in the AppCenter. Let's do this thing!

(disclaimer: obviously, you guys are a little better at design than I am, so maybe you have a better idea where to place the button, but I really think there should be a simple, integrated button somewhere non-intrusive)

**Comment by cassidyjames** [comment]
Thanks for the issue @h4ck3r9! This is something we've discussed before and I think are on board with. We'd probably go for a similar setup as AppCenter with a "Fund" button (since we can't consider payments to be charitable donations) and the StripeDialog from AppCenter.

Once we store payment info, it'd even be possible to reuse payment methods that have been used in AppCenter.

**Comment by h4ck3r9** [comment]
Oh man! If you guys allowed storing credit card info, that would be awesome! I know I'm not the only guy out here, so if there is a way to store it locally instead of through Stripe, that would be awesome too.

**Comment by ryonakano** [comment]
We have a button that jumps to https://elementary.io/get-involved, which is added in #325. Maybe we can close this issue in favor of that?
