### ISSUE TITLE
Show what kind of storage is used

### ISSUE THREAD

**Issue by ryonakano** [elementary/switchboard-plug-about#63]
This may not be always necessary, but if we can check I suppose it's nice:
e.g. SATA HDD, SATA SSD, or NVMe SSD

**Comment by marcelogdeandrade** [comment]
I'm working on this. The first solution I found was reading this file:

$ cat /sys/block/sda/queue/rotational

as explained in [this](https://unix.stackexchange.com/questions/65595/how-to-know-if-a-disk-is-an-ssd-or-an-hdd) post.

The problem is, it only works if the mounted device's name is "sda" but I think I can get around it looking for the devices's name before searching this file.

**Comment by marcelogdeandrade** [comment]
@danrabbit I solved this issue of finding out the disk's name executing "$ df /". But I don't know if it is possible or recommended to execute a command inside an elementary application.

Can I take this approach or should I try to solve it by getting this information from a system file?
